export const ACTION_TYPE = {
	COMMENT_REMOVE: 'COMMENT_REMOVE',
	COMMENTS_SET: 'COMMENTS_SET',
	COMMENT_ADD: 'COMMENT_ADD',
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_POST_DATA: 'SET_POST_DATA',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	RESET_POST_DATA: 'RESET_POST_DATA',
};

