services:
  date:
    build:
      context: ./date-service
      dockerfile: Dockerfile
    container_name: date-service
    image: mailtime2010/student-date:latest

  result:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    container_name: result-service
    image: mailtime2010/student-result:latest
    env_file:
      - .env
    depends_on:
      - date

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    image: mailtime2010/student-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
    depends_on:
      - result

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
    # этот сервис используем только вручную для первого получения сертификата:
    # docker compose run --rm certbot certonly ...

