services:
  date:
    container_name: date-service
    image: mailtime2010/student-date:latest
    env_file:
      - .env

  result:
    container_name: result-service
    image: mailtime2010/student-result:latest
    env_file:
      - .env
    depends_on:
      - date

  nginx:
    container_name: nginx
    image: mailtime2010/student-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
    depends_on:
      - result

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt

  certbot-renew:
    image: certbot/certbot
    container_name: certbot-renew
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      sh -c 'while :; do
        certbot renew --webroot -w /var/www/certbot &&
        docker exec nginx nginx -s reload;
        sleep 12h;
      done'
    depends_on:
      - nginx

