services:
  date:
    build:
      context: ./date-service
      dockerfile: Dockerfile
    container_name: date-service

  result:
    build:
      context: ./result-service
      dockerfile: Dockerfile
    container_name: result-service
    depends_on:
      - date

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx-local/default-local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - result