let userString = prompt('Введите текст для обрезки');
let startSliceIndex = prompt('Введите индекс, с которого нужно начать обрезку строки');
let endSliceIndex = prompt('Введите индекс, которым нужно закончить обрезку строки');
userString = userString.trim();
startSliceIndex = startSliceIndex.trim();
endSliceIndex = endSliceIndex.trim();
startSliceIndex = Number(startSliceIndex);
endSliceIndex = Number(endSliceIndex);
startSliceIndex = !Number.isNaN(startSliceIndex) ? startSliceIndex : 0;
endSliceIndex = !Number.isNaN(endSliceIndex) ? endSliceIndex : userString.length;
let string = userString.slice(startSliceIndex, endSliceIndex);
alert(`Результат: ${string}`);
