export const TYPE = {
	UPDATE_FIELDS: 'UPDATE_FIELDS',
	INIT_FIELDS: 'INIT_FIELDS',
	DRAW_TRUE: 'DRAW_TRUE',
	DRAW_FALSE: 'DRAW_FALSE',
	GAME_END_TRUE: 'GAME_END_TRUE',
	GAME_END_FALSE: 'GAME_END_FALSE',
	SET_PLAYER: 'SET_PLAYER',
	INIT_PLAYER: 'INIT_PLAYER',
	INCREMENT_SCORE: 'INCREMENT_SCORE',
};
