import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       content,
                                       sidebar,
                                       modal
                                   }: Readonly<{
    children: React.ReactNode;
    content: React.ReactNode;
    sidebar: React.ReactNode;
    modal: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
            Shared Header for all Pages
        </header>
        <hr/>
        <div style={{display: 'flex', height: "100vh"}}>
            <aside style={{width: 250, borderRight: '1px solid #ddd'}}>{sidebar}</aside>
            <main style={{flex: 1, position: 'relative', padding: 20}}>
                {content} {children}
            </main>
        </div>
        {modal}
        </body>
        </html>
    );
}
