export const ACTION_TYPE = {
	SET_TEST_DATA: 'SET_TEST_DATA',
	STUB_QUESTION: 'STUB_QUESTION',
	UPDATE_QUESTION: 'UPDATE_QUESTION',
	STUB_ANSWER: 'STUB_ANSWER',
	REMOVE_ANSWER: 'REMOVE_ANSWER',
	REMOVE_QUESTION: 'REMOVE_QUESTION',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
};
